version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Manual-Deployment-Backend
    overwrite: true
files_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/application_start.sh
      timeout: 300
      runas: root